"""catalog_name_unique

Revision ID: 9ac9430ecc6c
Revises: 7754194262d1
Create Date: 2026-04-01 15:37:27.065470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac9430ecc6c'
down_revision: Union[str, Sequence[str], None] = '7754194262d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogs_name'), table_name='catalogs')
    op.create_index(op.f('ix_catalogs_name'), 'catalogs', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogs_name'), table_name='catalogs')
    op.create_index(op.f('ix_catalogs_name'), 'catalogs', ['name'], unique=False)
    # ### end Alembic commands ###
